version: '3.8'

services:
  db:
    image: postgres:15
    container_name: medflow_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: medflow_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./src/config/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: .
    container_name: medflow_backend
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://admin:password123@db:5432/medflow_db
      JWT_SECRET: amazing_fantasy_15
      PORT: 10000
    ports:
      - "10000:10000"

volumes:
  pgdata: